name: Flask CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t flask-lab-app:${{ github.sha }} .
        
    - name: Test Docker image
      run: |
        docker run -d -p 5000:5000 --name test-container flask-lab-app:${{ github.sha }}
        sleep 10
        docker ps
        # Test if container is responding
        docker exec test-container curl -f http://localhost:5000/health || echo "Container health check failed"
        docker stop test-container
        docker rm test-container

  # Optional: Push to Docker Hub
  # push-to-dockerhub:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     
  #   - name: Log in to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #       
  #   - name: Build and push
  #     uses: docker/build-push-action@v4
  #     with:
  #       context: .
  #       push: true
  #       tags: your-dockerhub-username/flask-lab-app:latest